/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  courseUp: [{type: 'autogenerated', dirName: 'course-up'}],
  vikelabsCa: [{type: 'autogenerated', dirName: 'vikelabs-ca'}],
  template: [{type: 'autogenerated', dirName: 'template'}],
};

module.exports = sidebars;
